name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Runs a single command using the runners shell
    - name: setup git config
      run: |
        git config user.name "Sadanand Pai"
        git config user.email "sadypai@gmail.com"
        
    - name: setup deployment
      run: |
        cd react
        npm install
        rm -rf dist
        npm run build
        git add dist -f
        git commit -m "build files from github action"
        git push
